[package]
name = "toshokan"
version = "0.1.0"
edition = "2021"
authors = ["Tony Solomonik @ tony.solomonik@gmail.com"]

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
serde_json = "1.0.117"
tantivy = "0.22.0"
