[package]
name = "toshokan"
version = "0.1.0"
edition = "2021"
authors = ["Tony Solomonik @ tony.solomonik@gmail.com"]

# https://github.com/eyre-rs/color-eyre#improving-perf-on-debug-builds
[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
strip = true
lto = true

[profile.release-thin-lto]
inherits = "release"
lto = "thin"

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.4", features = ["derive"] }
color-eyre = { version = "0.6.3", default-features = false }
itertools = "0.12.1"
log = "0.4.21"
once_cell = "1.19.0"
opendal = { version = "0.46.0", features = ["layers-blocking", "services-fs"] }
pretty_env_logger = "0.5.0"
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
tantivy = "0.22.0"
tokio = { version = "1.37.0", features = ["full"] }
uuid = { version = "1.8.0", features = ["v7"] }

[dev-dependencies]
tempfile = "3.10.1"
