[package]
name = "toshokan"
version = "0.1.0"
edition = "2021"
authors = ["Tony Solomonik @ tony.solomonik@gmail.com"]

[dependencies]
anyhow = "1.0.83"
bincode = "1.3.3"
clap = { version = "4.5.4", features = ["derive"] }
once_cell = "1.19.0"
opendal = { version = "0.46.0", features = ["layers-blocking", "services-fs"] }
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
tantivy = "0.22.0"
tokio = { version = "1.37.0", features = ["full"] }

[dev-dependencies]
tempfile = "3.10.1"
