version: 1
name: test
path: /tmp/toshokan
schema:
  time_field: timestamp
  fields:
    - name: timestamp
      type: !datetime
        formats:
          - timestamp
        indexed: true
        stored: true
        fast: true
    - name: tenant_id
      type: !number
        type: u64
    - name: resource
      type: !dynamic_object
        expand_dots: true
    - name: attributes
      type: !static_object
        fields:
          - name: class
            type: !text
