version: 1
name: test
path: /tmp/toshokan
schema:
  time_field: timestamp
  fields:
    timestamp:
      type: !datetime
        formats:
          - timestamp
        indexed: true
        stored: true
        fast: true
    tenant_id:
      type: !number
        type: u64
    resource:
      type: !dynamic_object
        expand_dots: true
